### PR TITLE
Tree with only one branch overlays the objects.

### PR DESCRIPTION
**Pull request by jfrickson**
The Y coordinate gets set to zero for all children/grandchildren, etc.

### CODE REVIEW

**Comment by jfrickson** [comment]
Sorry, that wasn't the problem

**Comment by mbostock** [comment]
This looks like a duplicate of #2650 (which was retracted by the author… I haven’t had time to investigate why). Appears to be a fix for #2646, also.

**Comment by jfrickson** [comment]
Ok, I also put in a fix for his and vylan's "root only node" problem.

**Comment by vylan** [comment]
Thanks @jfrickson , I 've tested with your code. I believe it fixed the issue. by the way, please change seq2 to sep2.

**Comment by jfrickson** [comment]
Should be good to go!

**Comment by mbostock** [comment]
I’ve pushed a slightly simpler fix in d3/d3-hierarchy@68055b9d22b2b1f002fd2cc1995238cbb778f644 for 4.0. In the case of a single-branch tree, the left- and right-most node is always the root, and I think it’s best to avoid invoking the separation function when *a* and *b* are the same node (the root); in that case, we can simply center the tree within the layout area.

I’m probably not going to back-port the fix to 3.x. A simple workaround is to not return Infinity from the separation function:

```js
function separation(a, b) {
  return (a.parent === b.parent ? 1 : 2) / Math.max(1, a.depth);
}
```

**Pull request closed without merging**
