### PR TITLE
Add packaging for Meteor.js.

### PR DESCRIPTION
**Pull request by dandv**
Hi Mike, Jason,

I'm a package maintainer for [Meteor.js](http://meteor.com), a [popular full-stack JavaScript framework](http://github.com/meteor/meteor).

Meteor devs love d3. It was a [core package](https://github.com/meteor/meteor/issues/2557) until recently, and now it's time to separate concerns and let the community maintain the Meteor <-> d3 integration. This PR will allow you to directly publish updated versions of d3 as they become available. All you have to do is create an account at https://meteor.com/ (click *SIGN IN*, then *Create account*). After you've done that, please let me know the name of the account, and I'll add you as a maintainer.

I've already published the current version of the package on [Atmosphere](https://atmospherejs.com/d3js/d3) (Meteor's package directory). When you release new versions of d3, you'll be able to publish them to Atmosphere by running `make meteor`.

Thanks & best regards,
Dan

### CODE REVIEW

**Comment by mizzao** [comment]
Hey guys - did you decide anything on this? Are we making something to slurp up the d3 releases as they come out, or is d3 just going to `make meteor`?

@mbostock - one important reason to have a single package is to avoid having a large number of poorly maintained third-party d3 wrapper packages in the Meteor ecosystem. Meteor's built-in version of d3 is pegged to `3.1.4` and won't ever be updated - it's been deprecated in favor of the community releasing their own, and we're trying to do it the canonical way instead of having irregular, manually updated releases.

**Comment by bobiblazeski** [comment]
Any update regarding this? Atmosphere version is outdated, while it claims to be the official version which makes things confusing.

**Comment by mbostock** [comment]
Sorry, but I haven’t had any time to work on this.

**Comment by dandv** [comment]
@bobiblazeski - I've just published the latest version on Atmosphere. Going forward, we're moving packages to an automatic publish framework, http://autopublish.meteor.com.

@mbostock: please let us know when you have a chance if you'd be open in principle to including `make meteor` in your build process. If not, no problem - we'll separate the Meteor wrapper into [its own repo](https://github.com/MeteorPackaging/d3), and trigger builds using the autopublish framework mentioned above (credits go to @splendido for that).

**Comment by splendido** [comment]
Hei @dandv and @mbostock, lets have a look at what we did with Twix,js:
- we've added a [package.js](https://github.com/icambron/twix.js/blob/master/package.js) file to the other PM ones
- and modified the [Makefile](https://github.com/icambron/twix.js/blob/master/Makefile)

This would be more than enough to work for autopublish.meteor.com
...unless there are particular actions to be taken to make the package compatible for Meteor!

**Comment by splendido** [comment]
...ok, sorry, I've seen only now that `bower.json` and `package.json` are generated from the scripts under  bin.
I guess we could do the same for the `pacakge.js` file?

Also there might be no need to tweak the export, since from the closure `this.d3` should already result as a global `d3` variables. Hence no need to have a [api.export('d3');](https://github.com/MeteorPackaging/d3/blob/meteor-integration/meteor/package.js#L18).
But I'd have to confirm this...

**Comment by bobiblazeski** [comment]
@mbostock Thank you for the  great work with d3.     
@dandv Thank you for the update.

**Comment by splendido** [comment]
Hello Mike and Jason,

following the above discussion I've just updated this PR (and in agreement with @dandv) to make it as lean as possible.

I plugged in your building process adding one more target to the `Makefile` so to get a `package.js` file automatically generate on new builds.

The idea is to leverage [autopublish.meteor.com](http://autopublish.meteor.com/) so that you won't have to run any additional commands (nor scripts) on your side to get the meteor package updated at every new release.

All you'll have to do, after having merged this PR, is going to [autopublish.meteor.com](http://autopublish.meteor.com/) sign in with your gitHub account, locate this repository and enable it for autopublish by toggling the checkbox you'll find on the right side of the repository item.

You can get an idea about how all this works by having a quick look at [this page](http://autopublish.meteor.com/howitworks), but basically it creates a [web hook](https://help.github.com/articles/about-webhooks/) on the repo to let us know when you push new tags. And when you'll release new versions, autopublish.meteor.com will automatically take delivery for publishing the new version also for Meteor!
...this is exactly what you were asking for in [this comment](https://github.com/mbostock/d3/pull/2130#issuecomment-64965388) so I hope you'll find this new updated PR well in line with your thinking.

Please note that you will not be able to toggle your repository until you'll have the `package.js` file on your master branch (without it the repo won't be recognized as a meteor package...).

Besides this, @dandv already did the other part of the job creating the `d3jd` organization including your `mbostock` user among the maintainers.

Thanks & best regards,
Luca & the [Meteor integration team](https://github.com/raix/Meteor-community-discussions/issues/14)

**Comment by mbostock** [comment]
Hi @splendido. Thanks for the update. The pull request looks good, but I’m not comfortable giving autopublish.meteor.com permissions to “read and write all public repo data”. If that means I just run `meteor publish` instead, I guess that’s okay.

**Comment by paralin** [comment]
@mbostock @splendido Is it really not possible to make this completely external and not require any repo access?

**Comment by splendido** [comment]
Giving permissions away is always something that can create concerns, I know.
This is why, in more recent PRs, I've added another paragraph to the instructions:

> In case you're not comfortable with autopublish.meteor.com maintaining access rights to your repos, please head to [GitHub Application Settings](https://github.com/settings/applications) and revoke permissions for *Meteor Autopublish*.

The only thing that *autopublish.meteor.com* does is creating a new webhook on the repository (for which write permissions are required...) and this is once for all.

@mbostock the other solution might be manually creating the webhook, but I would have to add some code to *autopublish.meteor.com* to pick up the first test payload as a new *registration* (I'll be happy to do it...)

If you still have concerns and you don't mind doing it, running `meteor publish` after the build would be enough (I guess your meteor.com user was already added to the package maintainers).

Among the three I'd prefer the second one to get the webhook, but feel free to go for the third (or the first one ;-) ): I'm open to every solution.

What do you think @paralin?

Thanks for the positive feed-back @mbostock !

**Comment by paralin** [comment]
@splendido The new registration through webhook sounds like a good compromise for paranoid repo owners. I'd add that option for sure.

**Comment by splendido** [comment]
I think @mbostock is doing very well being *paranoid* about his repos ;-)
If we think creating a new subscription on autopublish.meteor.com when the test trigger for a new hook arrives can be a good solution, I'll try to play with it during the next week.

Lets see what @mbostock think about giving permissions for a few minutes only.

Thanks again,
Luca

**Comment by mbostock** [comment]
Yeah, I’m afraid I would not be comfortable giving an untrusted party full write permissions to all my public repositories, even temporarily. :tinhat:

**Comment by splendido** [comment]
Don't worry, it's all fine.
I appreciate your line about repository protection!

If after merging this PR you could cretae a new JSON webhook pointing to:

```
http://autopublish.meteor.com/publish
```

that would be more than enough anf much appreciated!

**Comment by splendido** [comment]
webhook

**Comment by mbostock** [comment]
You want the Release event, no?

**Comment by splendido** [comment]
Yeah, in your case Release is fine!
(not all are using releases, someone just push tags...)

**Comment by mbostock** [comment]
OK, merged. Thank you!

**Comment by splendido** [comment]
Thank you @mbostock!

I really appreciate your collaboration, hopefully we'll not have to bother you again with this :)
...I'll work on the webhook test trigger on my side: I think this will be useful for other cases as well.

Keep up the great work!

Luca

**Comment by mbostock** [comment]
Question: where does Meteor pull the generated `d3.js` file from? I’m planning on removing this file from the git repository in the future (#2226). It’ll only be available in the d3.zip attached to the release or the published NPM package.

**Comment by splendido** [comment]
mmm, that might become a problem :(

At the moment it picks up the `d3.js` file on the root folder: see [this line](https://github.com/mbostock/d3/blob/master/package.js#L12)

But if it will be still generated with the build process we might trigger the build soon after the repo is cloned on the build machine and before running `meteor publish`.

We should be warned about this change with a failure on the publish operation ;-)

**Comment by mbostock** [comment]
> But if it will be still generated with the build process we might trigger the build soon after the repo is cloned on the build machine and before running meteor publish.

I don’t think you want to run my build process on your machine. That would be insecure for you. And bad for me, since it does not guarantee that the published file you build is the same as my official release.

So, I guess we’re back to me running `meteor publish`. That’s fine, I guess. Looks like I won’t be able to delete the generated files until Bower supports its own registry, anyway.

**Comment by splendido** [comment]
Ok, I'll keep an eye on this.
Please feel free to delete the webhook when you'll remove the `d3.js` file from the repo.

Thank you again!
Luca

**Comment by mbostock** [comment]
So, now that was merged, can we make `meteor add d3` an alias for `meteor add d3js:d3`? The old built-in is deprecated and out-of-date, but still referred to documentation. It’d be nice if it now pointed to the official release.

**Comment by splendido** [comment]
I'll try to see whether we can get the older one(s) flagged or set as unmigrated (hidden).

You might also go to [atmosphere](https://atmospherejs.com/meteor/d3) and flag it: the sooner we get enough flags, the sooner the package will be marked as flagged.

...and there's no way to get an alias for the new name. The `meteor add d3` withouth author name was something in use before Meteor@0.9.0 :(

**Comment by mbostock** [comment]
> ...and there's no way to get an alias for the new name.

Sure there is! It’s just code, right? :grin: I mean, it’s up to the Meteor team as to whether it’s better

(A) to have `meteor add d3` not work at all,
(B) to install an old release, or
(C) to install the latest release.

I’m merely suggesting that installing the latest release (C) might be the best option.

If you want to make it not work (A), that sounds fine, too. But silently installing an old release (B) seems like the worst of the three. There’s not even any information on [the meteor/d3 package](https://atmospherejs.com/meteor/d3) about it being deprecated and out-of-date.

**Comment by splendido** [comment]
Your analysis is totally correct!
But I think our best option is to open an issue on the Meteor repository asking MDG to remove they're d3 package since it's no more officially supported and not up to date.

Would you like me to create the new issue?
...it might have more weight if you do it yourself though. And I'll be happy to second you!

**Comment by splendido** [comment]
Actually there are already a number of issues about this topic...
See [this search](https://github.com/meteor/meteor/issues?q=is%3Aissue+d3+is%3Aclosed).

And @dandv [pinged them very recently](https://github.com/meteor/meteor/issues/3082#issuecomment-73470690) after you merged this.

**Comment by splendido** [comment]
The latest release was correctly signalled to autopublish.meteor.com but the user `meteorpublish` is still not part of the `d3js` organization. This is the error that was signalled:

```
error: You are not an authorized maintainer for this package.
```

@dandv could you add `meteorpublish` to `d3js` so that I can retrigger the publish?

**Comment by mbostock** [comment]
I setup a `publish` target in the Makefile, so I’m planning on just doing manual publishes (at the same time I publish to NPM). I’ll remove the Webhook.

**Comment by dandv** [comment]
@splendido: added you and meteorpublish as well, even if no longer necessary if Mike will be publishing manually.

**Comment by splendido** [comment]
Ok, I'm going to remove d3js:d3 from autopublish then.
No worries.

Thank you @mbostock for taking the publish process on you!

**Comment by garrilla** [comment]
where are we up to with this?

the current version on the meteor packagaing system is at 3.5.5

**Comment by mcinano** [comment]
Hi everyone
Is there any plan to update the atmosphere repo to d3 4.x?

**Comment by mbostock** [comment]
I am no longer supporting any publishing systems beyond npm and GitHub, but anyone else is welcome to make D3 available on other systems.

**Comment by paralin** [comment]
Meteor supports npm, use it! :)

**Comment by mcinano** [comment]
Thx, I'll use npm package.
So should be d3 removed from atmospherejs.com?

**Comment by dandv** [comment]
@mcinano Probably. Though I don't know what the solution is for people who just search Atmosphere for 3rd party libraries and instead of our well-maintained wrapper packages, they find old, unmaintained, thin wrappers. See https://github.com/percolatestudio/atmosphere/issues/403.

**Pull request merged**
