### PR TITLE
Suitably zealous click canceling.

### PR DESCRIPTION
**Pull request by mbostock**
This reverts #312, since we later implemented a more robust check in #1005 using a zero-delay timeout to expire click suppression.

### CODE REVIEW

**Comment by mbostock** [comment]
Merged into #2638 for 3.5.9.

**Comment by JesperWe** [comment]
Was this supposed to fix the defaultPrevented problem on Chrome? I use a zoom behaviour with drag for panning, and need to recognize clicks as well. I am on 3.5.16 now, and I still have issues with Chrome always setting defaultPrevented = true, both on drags and clicks, which means I can't tell them apart. Firefox works fine, sets defaultPrevented = false for clicks.

**Comment by mbostock** [comment]
Works for me? ¯\\\_(ツ)\_/¯

http://bl.ocks.org/mbostock/a84aeb78fea81e1ad806

**Comment by JesperWe** [comment]
OK, my case is different: I have a zoom behavior, where a drag does panning, but a click should do something else. In this case both a single click and a drag event triggers a 'click', which comes with `defaultPrevented=true` for **both** types of operation on Chrome, but `defaultPrevented=false` for the single click and `defaultPrevented=true` for the drag on Firefox and Edge. Maybe this is a different issue?

**Comment by mbostock** [comment]
Still works for me with zoom? ¯\\\_(ツ)\_/¯

http://bl.ocks.org/mbostock/35964711079355050ff1

**Comment by JesperWe** [comment]
Right. I have spent the day investigating this. Before this commit, my app was intermittently buggy. With this patch it stopped being intermittent, so it was easier to debug. I had the `.on( 'click' )` on the `<svg>`, and the `.call(zoomBehavior)` on a `<g>` tag inside it. With this setup there is a difference between Chrome and other browsers. When I moved the click to the same tag as the zoom, it starts to work as expected.

**Comment by ljani** [comment]
I just tried the [Zoom vs. Drag](http://bl.ocks.org/mbostock/35964711079355050ff1) example and it doesn't work for me with Chrome 50.0.2661.102 m on Windows 10. I'm only able to zoom and pan.

Updating to Chrome 51.0.2704.63 m seems to fix the issue, but it's very new and not everyone has updated yet.

**Comment by mbostock** [comment]
That sounds like the expected behavior for that example; I’ve just renamed it Zoom vs. Click to make the intent clearer. It is not intended to allow dragging of individual circles; it is intended to demonstrate how to allow clicks on a zoomable element.

Here’s a [zooming and dragging example](https://bl.ocks.org/mbostock/6123708) in D3 3.x.

Here’s a [zooming and dragging example](http://bl.ocks.org/mbostock/2b534b091d80a8de39219dd076b316cd) in D3 4.0.

**Comment by ljani** [comment]
@mbostock I thought the background was supposed to flash if you clicked it? With Chrome, there are times when it won't flash even if I clicked anywhere. Most of the time it works just fine.

**Comment by mbostock** [comment]
It only flashes if you click on the background. Furthermore, if you move the mouse at all between mousedown and mouseup, it won’t count as a click because it is interpreted as a (tiny) drag gesture. If you have a particularly sensitive mouse, it’s possible that you’re seeing a tiny bit of mouse movement just in a normal mousedown and mouseup. This is one reason not to try to support both clicking and zooming: it’s inherently ambiguous.

Right-clicking is probably an unrelated issue. The zoom behavior doesn’t ignore right clicks by default in 3.x; it does in 4.0.

**Comment by ljani** [comment]
Yeah, I meant the background. And I agree with your thoughts about clicking and zooming.

Here's another thing: Tooltips. Consider [this example](http://bl.ocks.org/ljani/7d11c3fb9ab99776f95e3b861f61706b). If you:

1. Point to a circle so that it'll display a tooltip (= the `<title>`)
2. Move your cursor over the white background
3. Click it, nothing happens on Chrome. On Firefox, the background flashes.

**Comment by ljani** [comment]
Here we go: https://gfycat.com/SolidFabulousHorsefly
Each time I click the background, `defaultPrevented` is logged to the console. I'm still not sure how to end up here, but it seems that leaving Chrome open and doing other stuff seems to be the key, heh.

**Pull request closed without merging**
