### PR TITLE
Variable update

### PR DESCRIPTION
**Pull request by tvictory**
Updated variables in the color class to add clarity to the variable names at a quick glance, as the subject matter can be confusing as it is. The appropriate documentation will be updated if this pull request is accepted.

### CODE REVIEW

**Comment by alanvanbuuren** [comment]
Thnx for the new variable name's

**Comment by mbostock** [comment]
This code has already been rewritten for D3 4.0 (see [d3-color](https://github.com/d3/d3-color)) so I will not be accepting style-only changes.

**Comment by mbostock** [comment]
Apologies for the terse response; I was distracted by my three-year-old. I appreciate your offer to make the code clearer and I’m sorry I’m not able to accept your request.

Code clarity is a matter of taste, and I don’t feel that these changes are universal improvements; I prefer shorter variable names when the meaning is already apparent from context, such as the R, G and B channels of the RGB color space.

That said, I know that sometimes I try too hard to make the code concise and that can make it harder to follow, and there could be some improvements I would accept. I’ve implemented a few changes in d3-color for 4.0 to make it more readable already, such as separating color space conversion, as in `hslConvert(color)`, from the color specification, as in `hsl(h, s, l, a)`.

If there are other changes you think might improve readability, please let me know. Although it may be best to smart small and discuss it early. Thank you.

**Comment by tvictory** [comment]
I appreciate your feedback and will consider taking a look at things in d3-color 4.0 instead then.

**Pull request closed without merging**
