### PR TITLE
Adds support for domainSegmented() on quantitative scales.

### PR DESCRIPTION
**Pull request by cscheid**
`domainSegmented()` splits the domain in segments which "walk the range at uniform speed". This means that if one replaces a 2-segment range [mn, mx] with a uniformly-split range [mn, ..., mx] of length l, then replacing the domain [mnD, mxD] with domainSegmented([mnD, mxD], l) will have no effect.

This transformation is useful when the range of a scale is (say) a highly-segmented colorbrewer scale, and one wishes to interpolate between the endpoints at the appropriate speed. More concretely, it allows one to easily change a colormap from:

`d3.scale.linear().domainSegmented([mnD, mxD], 6).range(colorbrewer.Blues[6])`

to

`d3.scale.log().domainSegmented([mnD, mxD], 6).range(colorbrewer.Blues[6])`

or

`d3.scale.pow().exponent(.5).domainSegmented([mnD, mxD], 6).range(colorbrewer.Blues[6])`

and the domain segments are split correctly.

### CODE REVIEW

**Comment by cscheid** [comment]
Hey, I don't know if this would be a sufficiently useful feature, but I've found myself reimplementing it a few times when exploring different nonlinear transformations over segmented ranges. I didn't find anything quite like it on the issues browser or documentation, but I apologize if this feature exists somewhere.

**Comment by mbostock** [comment]
Did you consider using a quantize scale? Quantize scales don’t (yet) support log and power transforms, but they achieve a similar effect. The main difference is that they will only output the discrete values in your range (e.g., the six colorbrewer blues), rather than interpolating continuously in-between.

**Comment by cscheid** [comment]
I did. I agree with you that in many (most, even) cases the quantize scales are the correct ones. But in this case (I'm building a time-varying 2d histogram) I was interested in observing the "movement" of the parts that would be "internal to the bands" as well.

But you're right that it might not be worth the trouble.

**Comment by mbostock** [comment]
Closing in favor of d3/d3-scale#45, as any future API changes will happen in d3-scale.

**Comment by mbostock** [comment]
My guess is that the new continuous sequential color scales derived from ColorBrewer in [d3-scale-chromatic](https://github.com/d3/d3-scale-chromatic) will be more appropriate for this use case, but there’s still the issue that you can’t easily apply a log or pow transform to a sequential scale (d3/d3-scale#62).

**Pull request closed without merging**
