### PR TITLE
Update README.md with serial comma

### PR DESCRIPTION
**Pull request by wcwung**
Update README.md to include a serial comma to better resolve ambiguity between the three terms HTML, SVG, and CSS. [Wikipedia](http://en.wikipedia.org/wiki/Serial_comma) states that an *omission* of a comma before the last term can suggest a stronger connection between the last two items in a series.

### CODE REVIEW

**Comment by mgold** [comment]
+1 Minor but correct.

**Comment by DannyDelott** [comment]
+1 for the Oxford comma.

**Comment by awelch83** [comment]
@mbostock Do pull requests actually get merged here? Or is submitting one mostly a waste of time?

**Comment by mbostock** [comment]
@awelch83 I’ve merged hundreds of d3-related pull requests.

**Comment by mbostock** [comment]
I made the corresponding to d3js.org as well.

**Pull request merged**
