### PR TITLE
Changed subject of last sentence to be D3.

### PR DESCRIPTION
**Pull request by mrblueblue**
Currently, the subject of the readme's last sentence is "D3's emphasis," which is bit abstract for a subject. Foregrounding D3 and having it as the main actor would make the sentence stronger and clearer.

Additionally, the adverbial clause (begins with "combing...") is a little odd. I moved this adverbial clause to the beginning to clarify the relationship between "combining" and "D3." Currently, the clause is modifying the verb "gives," but placing it after "framework" makes it seem like its actually modifying "framework." 

In any case, I just felt that the last sentence was a little long and odd, so I'm proposing these changes and hoping that you find them helpful.

### CODE REVIEW

**Comment by mrblueblue** [comment]
One aspect I really liked about the old readme is that all three sentences started with "D3."

In order to preserve this repetitive structure, I've updated my pull request. It now reads:

**D3.js** is a JavaScript library for manipulating documents based on data. **D3** helps you bring data to life using HTML, SVG, and CSS. **D3** emphasizes web standards and combines powerful visualization components and a data-driven approach to DOM manipulation, giving you the full capabilities of modern browsers without tying yourself to a proprietary framework.

**Comment by jhamon** [comment]
I'm just passing through but wanted to say I :+1:  these changes.  I would have also changed:

> and combines powerful visualization components **and** a data-driven approach to DOM manipulation, giving  

to

> and combines powerful visualization components **with** a data-driven approach to DOM manipulation, giving  


The repeated use of `and` in that sentence doesn't really roll off the tongue.

**Comment by amZotti** [comment]
Why has this not been merged yet?

**Comment by mrblueblue** [comment]
I really like that change jhamon. The sentence now reads:
>and combines powerful visualization components with a data-driven approach to DOM manipulation, giving

**Comment by mbostock** [comment]
:+1:

**Pull request merged**
