### PR TITLE
Platlets

### PR DESCRIPTION
**Pull request by lokesh005**
Platlets is the extention of Pie-Chart on d3. Its a new chart having
attractive shape. If you want to know what the pie chart looks like
visit:http://bl.ocks.org/mbostock/3887235

For platelets visit: http://bl.ocks.org/lokesh005/1b23c84b68f5be134ff0

### CODE REVIEW

**Comment by lokesh005** [comment]
what does it mean

**Comment by mbostock** [comment]
Thank you for the contribution, but this would be better as an example (as you have already published on bl.ocks.org) rather than added to the git repository. Cheers!

**Comment by lokesh005** [comment]
Hey but why not it should be in your galary as this svg is unique

**Comment by lokesh005** [comment]
Please answer me

**Comment by mbostock** [comment]
Examples are added to the gallery by anyone editing the wiki: it’s publicly editable. You don’t need to submit examples as pull requests.

That said, I’m not convinced this is an effective design for visualization. The large rounded corners subtract more from the larger arcs than the smaller arcs. I don’t see why this is better than a standard pie or donut chart.

**Comment by lokesh005** [comment]
Okay thanks

**Pull request closed without merging**
