### PR TITLE
Added ability to specify additional size for hierarchical parents

### PR DESCRIPTION
**Pull request by mgetz**
First attempt to make the parents reflect their own size in addition to the size of their children. This is in response to issue #2247 and #1686. This is the same issue I faced as well. I had the additional problem where I could not drag and drop a circle into a parent with a single child since it was the same size.

### CODE REVIEW

**Comment by hughes** [comment]
This is great - hope to see it merged soon.

**Comment by hughes** [comment]
Meanwhile, @mbostock has an [example of creating padding with dummy nodes](http://bl.ocks.org/mbostock/3315318)

**Comment by mgetz** [comment]
Thanks for that example, Matt! I had not found that one.

**Comment by hughes** [comment]
It's not a great workaround honestly... the padding is only on one side and the resulting size can be difficult to predict.

**Comment by mbostock** [comment]
Moving to d3/d3-hierarchy#9. I feel like padding (d3/d3-hierarchy#7) is a better solution than internal node value, given the issues with trying to show internal node value meaningfully.

**Comment by ikari-pl** [comment]
This might seem a stupid question, but how can I currently force the `partition` layout, based on hiearchy as well, to use `size` for the parent nodes, *without* switching to `d3-layout`? The padding should be doable and is probably the only option for a sunburst, right?

**Pull request closed without merging**
